services:
  db:
    container_name: db
    networks:
      - delivery
    image: postgres:13.3
    environment:
      POSTGRES_DB: "delivery_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"

  back:
    container_name: back
    depends_on:
      - db
    networks:
      - delivery
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./service/web/src:/var/www/html

  front:
    container_name: front
    depends_on:
      - back
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - delivery

networks:
  delivery: